In [5]:
import pandas as pd
import matplotlib
import seaborn

In [6]:
df = pd.read_csv(r"C:\Users\DELL\OneDrive\Anaconda\Dikshaprj\archive\car_data.csv")

In [7]:
print(df.shape)

(42089, 13)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42089 entries, 0 to 42088
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           42089 non-null  int64
 1   car_brand            42089 non-null  object
 2   car_model            42089 non-null  object
 3   car_price            42089 non-null  int64
 4   car_city             42089 non-null  object
 5   car_fuel             42089 non-null  object
 6   car_transmission     42089 non-null  object
 7   car_drive            42089 non-null  object
 8   car_mileage          42089 non-null  int64
 9   car_country          42089 non-null  object
 10  car_engine_capacity  42089 non-null  float64
 11  car_engine_hp        42089 non-null  int64
 12  car_age              42089 non-null  int64
dtypes: float64(1), int64(5), object(7)
memory usage: 4.2+ MB

In [9]:
df.columns

Index(['Unnamed: 0', 'car_brand', 'car_model', 'car_price', 'car_city',
       'car_fuel', 'car_transmission', 'car_drive', 'car_mileage',
       'car_country', 'car_engine_capacity', 'car_engine_hp', 'car_age'],
      dtype='object')

In [10]:
df.columns.values
list(df.columns)

['Unnamed: 0',
 'car_brand',
 'car_model',
 'car_price',
 'car_city',
 'car_fuel',
 'car_transmission',
 'car_drive',
 'car_mileage',
 'car_country',
 'car_engine_capacity',
 'car_engine_hp',
 'car_age']

In [11]:
df.head()

,Unnamed: 0,car_brand,car_model,car_price,car_city,car_fuel,car_transmission,car_drive,car_mileage,car_country,car_engine_capacity,car_engine_hp,car_age
0,0,Ford,Focus,550000,Astrakhan,gasoline,manual,FWD,300000,USA,1.8,125,14
1,1,Mercedes-Benz,GLA-Class,1820000,Astrakhan,gasoline,robot,FWD,88000,DE,1.6,156,10
2,2,Haval,F7,2600000,Astrakhan,gasoline,robot,4WD,19000,CN,1.5,150,2
3,3,Toyota,Camry,4200000,Astrakhan,gasoline,automatic,FWD,30000,JP,3.5,249,2
4,4,OMODA,C5,2125000,Astrakhan,gasoline,CVT,FWD,18824,CN,1.5,147,2

In [12]:
df.head(10)

,Unnamed: 0,car_brand,car_model,car_price,car_city,car_fuel,car_transmission,car_drive,car_mileage,car_country,car_engine_capacity,car_engine_hp,car_age
0,0,Ford,Focus,550000,Astrakhan,gasoline,manual,FWD,300000,USA,1.8,125,14
1,1,Mercedes-Benz,GLA-Class,1820000,Astrakhan,gasoline,robot,FWD,88000,DE,1.6,156,10
2,2,Haval,F7,2600000,Astrakhan,gasoline,robot,4WD,19000,CN,1.5,150,2
3,3,Toyota,Camry,4200000,Astrakhan,gasoline,automatic,FWD,30000,JP,3.5,249,2
4,4,OMODA,C5,2125000,Astrakhan,gasoline,CVT,FWD,18824,CN,1.5,147,2
5,5,Mercedes-Benz,E-Class,3779999,Astrakhan,gasoline,automatic,4WD,125000,DE,2.0,184,6
6,6,Toyota,RAV4,2539000,Astrakhan,gasoline,CVT,FWD,68023,JP,2.0,146,9
7,7,Ford,Focus,555000,Astrakhan,gasoline,manual,FWD,261000,USA,1.8,125,18
8,8,Honda,Civic,455000,Astrakhan,gasoline,automatic,FWD,250000,JP,1.5,105,22
9,9,Kia,Rio X (X-Line),1950000,Astrakhan,gasoline,automatic,FWD,40000,KR,1.6,123,5

In [13]:
df.tail()

,Unnamed: 0,car_brand,car_model,car_price,car_city,car_fuel,car_transmission,car_drive,car_mileage,car_country,car_engine_capacity,car_engine_hp,car_age
42084,42084,Isuzu,Bighorn,450000,Yakutsk,diesel,automatic,4WD,183212,JP,3.1,125,30
42085,42085,Toyota,Corolla Axio,650000,Yakutsk,gasoline,CVT,FWD,110000,JP,1.5,110,13
42086,42086,Daihatsu,Be-Go,1350000,Yakutsk,gasoline,automatic,4WD,153000,JP,1.5,109,13
42087,42087,Mazda,Tribute,550000,Yakutsk,gasoline,automatic,4WD,190000,JP,2.0,129,23
42088,42088,Lexus,GX460,4000000,Yakutsk,gasoline,automatic,4WD,217000,JP,4.6,296,13

In [14]:
df.tail(10)

,Unnamed: 0,car_brand,car_model,car_price,car_city,car_fuel,car_transmission,car_drive,car_mileage,car_country,car_engine_capacity,car_engine_hp,car_age
42079,42079,Honda,Logo,150000,Yakutsk,gasoline,automatic,FWD,200000,JP,1.3,66,25
42080,42080,Daewoo,Nexia,730000,Yakutsk,gasoline,manual,FWD,8000,KR,1.6,109,13
42081,42081,Toyota,Probox,1250000,Yakutsk,gasoline,CVT,FWD,175000,JP,1.5,109,7
42082,42082,Nissan,Presage,550000,Yakutsk,gasoline,automatic,FWD,166000,JP,2.5,165,23
42083,42083,Toyota,Noah,2100000,Yakutsk,hybrid,CVT,FWD,70000,JP,1.8,99,10
42084,42084,Isuzu,Bighorn,450000,Yakutsk,diesel,automatic,4WD,183212,JP,3.1,125,30
42085,42085,Toyota,Corolla Axio,650000,Yakutsk,gasoline,CVT,FWD,110000,JP,1.5,110,13
42086,42086,Daihatsu,Be-Go,1350000,Yakutsk,gasoline,automatic,4WD,153000,JP,1.5,109,13
42087,42087,Mazda,Tribute,550000,Yakutsk,gasoline,automatic,4WD,190000,JP,2.0,129,23
42088,42088,Lexus,GX460,4000000,Yakutsk,gasoline,automatic,4WD,217000,JP,4.6,296,13

In [15]:
dd = df.drop_duplicates(keep='first')

In [16]:
dd

,Unnamed: 0,car_brand,car_model,car_price,car_city,car_fuel,car_transmission,car_drive,car_mileage,car_country,car_engine_capacity,car_engine_hp,car_age
0,0,Ford,Focus,550000,Astrakhan,gasoline,manual,FWD,300000,USA,1.8,125,14
1,1,Mercedes-Benz,GLA-Class,1820000,Astrakhan,gasoline,robot,FWD,88000,DE,1.6,156,10
2,2,Haval,F7,2600000,Astrakhan,gasoline,robot,4WD,19000,CN,1.5,150,2
3,3,Toyota,Camry,4200000,Astrakhan,gasoline,automatic,FWD,30000,JP,3.5,249,2
4,4,OMODA,C5,2125000,Astrakhan,gasoline,CVT,FWD,18824,CN,1.5,147,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42084,42084,Isuzu,Bighorn,450000,Yakutsk,diesel,automatic,4WD,183212,JP,3.1,125,30
42085,42085,Toyota,Corolla Axio,650000,Yakutsk,gasoline,CVT,FWD,110000,JP,1.5,110,13
42086,42086,Daihatsu,Be-Go,1350000,Yakutsk,gasoline,automatic,4WD,153000,JP,1.5,109,13
42087,42087,Mazda,Tribute,550000,Yakutsk,gasoline,automatic,4WD,190000,JP,2.0,129,23
42088,42088,Lexus,GX460,4000000,Yakutsk,gasoline,automatic,4WD,217000,JP,4.6,296,13

In [18]:
df.isnull().sum()

Unnamed: 0             0
car_brand              0
car_model              0
car_price              0
car_city               0
car_fuel               0
car_transmission       0
car_drive              0
car_mileage            0
car_country            0
car_engine_capacity    0
car_engine_hp          0
car_age                0
dtype: int64

In [19]:
df.sort_values(by='car_price',ascending=False)

,Unnamed: 0,car_brand,car_model,car_price,car_city,car_fuel,car_transmission,car_drive,car_mileage,car_country,car_engine_capacity,car_engine_hp,car_age
16651,16651,Rolls-Royce,Phantom,69999999,Moscow,gasoline,automatic,RWD,6500,UK,6.8,563,3
16654,16654,Mercedes-Benz,G-Class,69999999,Moscow,gasoline,automatic,4WD,772,DE,4.0,585,2
16645,16645,Rolls-Royce,Phantom,67800000,Moscow,gasoline,automatic,RWD,22000,UK,6.8,563,3
16646,16646,Ferrari,SF90 Stradale,59999999,Moscow,hybrid,robot,4WD,4500,IT,4.0,780,3
16644,16644,Mercedes-Benz,G-Class,55999999,Moscow,gasoline,automatic,4WD,1200,DE,6.0,630,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7534,7534,Lada,21099,35000,Yekaterinburg,gasoline,manual,FWD,230000,RUS,1.5,70,24
6132,6132,Lada,2107,30000,Nizhny Novgorod,gasoline,manual,RWD,100000,RUS,1.6,74,20
976,976,ZAZ,Zaporozhets,30000,Chita,gasoline,manual,RWD,100,RUS,1.2,41,46
37863,37863,ЛуАЗ,ЛуАЗ,30000,Blagoveshchensk,gasoline,manual,4WD,100000,UKR,1.0,200,40
10757,10757,Kia,Soul,7000,Kazan,gasoline,automatic,FWD,44000,KR,1.6,123,5

In [20]:
df['car_country'].unique()

array(['USA', 'DE', 'CN', 'JP', 'KR', 'FR', 'RUS', 'CZ', 'UK', 'UZ',
       'KR ', 'SE', 'ES', 'IT', 'IR', 'UKR'], dtype=object)

In [21]:
def origin_to_num(x):
    if x == "USA" : return 1
    if x == "DE" : return 2
    if x == "CN" : return 3

In [22]:
df.iloc[0]

Unnamed: 0                     0
car_brand                   Ford
car_model              Focus
car_price                 550000
car_city               Astrakhan
car_fuel                gasoline
car_transmission          manual
car_drive                    FWD
car_mileage               300000
car_country                  USA
car_engine_capacity          1.8
car_engine_hp                125
car_age                       14
Name: 0, dtype: object

In [23]:
df.iloc[0:5]

,Unnamed: 0,car_brand,car_model,car_price,car_city,car_fuel,car_transmission,car_drive,car_mileage,car_country,car_engine_capacity,car_engine_hp,car_age
0,0,Ford,Focus,550000,Astrakhan,gasoline,manual,FWD,300000,USA,1.8,125,14
1,1,Mercedes-Benz,GLA-Class,1820000,Astrakhan,gasoline,robot,FWD,88000,DE,1.6,156,10
2,2,Haval,F7,2600000,Astrakhan,gasoline,robot,4WD,19000,CN,1.5,150,2
3,3,Toyota,Camry,4200000,Astrakhan,gasoline,automatic,FWD,30000,JP,3.5,249,2
4,4,OMODA,C5,2125000,Astrakhan,gasoline,CVT,FWD,18824,CN,1.5,147,2

In [24]:
df.iloc[-1]

Unnamed: 0                 42088
car_brand                  Lexus
car_model              GX460
car_price                4000000
car_city                 Yakutsk
car_fuel                gasoline
car_transmission       automatic
car_drive                    4WD
car_mileage               217000
car_country                   JP
car_engine_capacity          4.6
car_engine_hp                296
car_age                       13
Name: 42088, dtype: object

In [28]:
df.iloc[1:,4:]

,car_city,car_fuel,car_transmission,car_drive,car_mileage,car_country,car_engine_capacity,car_engine_hp,car_age
1,Astrakhan,gasoline,robot,FWD,88000,DE,1.6,156,10
2,Astrakhan,gasoline,robot,4WD,19000,CN,1.5,150,2
3,Astrakhan,gasoline,automatic,FWD,30000,JP,3.5,249,2
4,Astrakhan,gasoline,CVT,FWD,18824,CN,1.5,147,2
5,Astrakhan,gasoline,automatic,4WD,125000,DE,2.0,184,6
...,...,...,...,...,...,...,...,...,...
42084,Yakutsk,diesel,automatic,4WD,183212,JP,3.1,125,30
42085,Yakutsk,gasoline,CVT,FWD,110000,JP,1.5,110,13
42086,Yakutsk,gasoline,automatic,4WD,153000,JP,1.5,109,13
42087,Yakutsk,gasoline,automatic,4WD,190000,JP,2.0,129,23
42088,Yakutsk,gasoline,automatic,4WD,217000,JP,4.6,296,13

In [ ]:
df